CREATE TABLE IF NOT EXISTS cargos (
    id_cargo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave VARCHAR(60) NOT NULL UNIQUE,
    nome VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS projetos (
    id_projeto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS permissoes (
    id_permissoes INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(60) NOT NULL,
    chave VARCHAR(1) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS clientes (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(110) NOT NULL,
    cnpj VARCHAR(14) NOT NULL UNIQUE,
    representante VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS divulgacoes (
    id_divulgacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave VARCHAR(60) NOT NULL UNIQUE,
    nome VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS prioridades (
    id_prioridade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(40) NOT NULL,
    valor INTEGER NOT NULL CHECK (valor >= 0)
);

CREATE TABLE IF NOT EXISTS checklists (
    id_checklist INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL UNIQUE,
    cargos_id_cargo INTEGER NOT NULL,
    projetos_id_projeto INTEGER NOT NULL,
    CONSTRAINT fk_usuarios_cargo
        FOREIGN KEY (cargos_id_cargo) REFERENCES cargos (id_cargo),
    CONSTRAINT fk_usuarios_projeto
        FOREIGN KEY (projetos_id_projeto) REFERENCES projetos (id_projeto),
    CONSTRAINT uq_usuarios_id_cargo
        UNIQUE (id_usuario, cargos_id_cargo)
);

CREATE TABLE IF NOT EXISTS tarefas (
    id_tarefa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cargo INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    prazo_inicial DATE NOT NULL,
    id_cliente INTEGER,
    id_projeto INTEGER,
    id_prioridade INTEGER,
    CONSTRAINT fk_tarefas_cargo
        FOREIGN KEY (id_cargo) REFERENCES cargos (id_cargo),
    CONSTRAINT fk_tarefas_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
    CONSTRAINT fk_tarefas_cliente
        FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente),
    CONSTRAINT fk_tarefas_projeto
        FOREIGN KEY (id_projeto) REFERENCES projetos (id_projeto),
    CONSTRAINT fk_tarefas_prioridade
        FOREIGN KEY (id_prioridade) REFERENCES prioridades (id_prioridade)
);

CREATE TABLE IF NOT EXISTS vagas (
    id_vaga INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo VARCHAR(80) NOT NULL,
    perfil_deixado VARCHAR(255) NOT NULL,
    prazo_inicial DATE NOT NULL,
    prazo_final DATE NOT NULL,
    id_divulgacao INTEGER NOT NULL,
    cand_inscritos INTEGER NOT NULL DEFAULT 0 CHECK (cand_inscritos >= 0),
    cand_ideias INTEGER NOT NULL DEFAULT 0 CHECK (cand_ideias >= 0),
    erros INTEGER NOT NULL DEFAULT 0 CHECK (erros >= 0),
    clientes_id_cliente INTEGER NOT NULL,
    usuarios_id_usuario INTEGER NOT NULL,
    usuarios_cargos_id_cargo INTEGER NOT NULL,
    CONSTRAINT ck_vagas_prazos CHECK (prazo_final >= prazo_inicial),
    CONSTRAINT fk_vagas_divulgacao
        FOREIGN KEY (id_divulgacao) REFERENCES divulgacoes (id_divulgacao),
    CONSTRAINT fk_vagas_cliente
        FOREIGN KEY (clientes_id_cliente) REFERENCES clientes (id_cliente),
    CONSTRAINT fk_vagas_usuario_cargo
        FOREIGN KEY (usuarios_id_usuario, usuarios_cargos_id_cargo)
        REFERENCES usuarios (id_usuario, cargos_id_cargo)
);

CREATE TABLE IF NOT EXISTS divulgacoes_has_vagas (
    divulgacoes_id_divulgacao INTEGER NOT NULL,
    vagas_id_vaga INTEGER NOT NULL,
    PRIMARY KEY (divulgacoes_id_divulgacao, vagas_id_vaga),
    CONSTRAINT fk_divulgacoes_vagas_divulgacao
        FOREIGN KEY (divulgacoes_id_divulgacao)
        REFERENCES divulgacoes (id_divulgacao)
        ON DELETE CASCADE,
    CONSTRAINT fk_divulgacoes_vagas_vaga
        FOREIGN KEY (vagas_id_vaga)
        REFERENCES vagas (id_vaga)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS usuarios_has_permissoes (
    usuarios_id_usuario INTEGER NOT NULL,
    permissoes_id_permissoes INTEGER NOT NULL,
    PRIMARY KEY (usuarios_id_usuario, permissoes_id_permissoes),
    CONSTRAINT fk_usuarios_permissoes_usuario
        FOREIGN KEY (usuarios_id_usuario)
        REFERENCES usuarios (id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT fk_usuarios_permissoes_permissao
        FOREIGN KEY (permissoes_id_permissoes)
        REFERENCES permissoes (id_permissoes)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS checklists_has_tarefas (
    checklists_id_checklist INTEGER NOT NULL,
    tarefas_id_tarefa INTEGER NOT NULL,
    PRIMARY KEY (checklists_id_checklist, tarefas_id_tarefa),
    CONSTRAINT fk_checklists_tarefas_checklist
        FOREIGN KEY (checklists_id_checklist)
        REFERENCES checklists (id_checklist)
        ON DELETE CASCADE,
    CONSTRAINT fk_checklists_tarefas_tarefa
        FOREIGN KEY (tarefas_id_tarefa)
        REFERENCES tarefas (id_tarefa)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_vagas_divulgacao
    ON vagas (id_divulgacao);

CREATE INDEX IF NOT EXISTS idx_vagas_cliente
    ON vagas (clientes_id_cliente);

CREATE INDEX IF NOT EXISTS idx_tarefas_usuario
    ON tarefas (id_usuario);

CREATE INDEX IF NOT EXISTS idx_tarefas_prioridade
    ON tarefas (id_prioridade);
